sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=multi-instance-centos-6
  - INSTANCE=multi-instance-centos-6 CHEF_VERSION=12.7.2
  - INSTANCE=multi-instance-centos-7
  - INSTANCE=multi-instance-centos-7 CHEF_VERSION=12.7.2
  - INSTANCE=multi-instance-debian-8
  - INSTANCE=multi-instance-debian-9
  - INSTANCE=multi-instance-fedora-latest
  - INSTANCE=multi-instance-opensuse-leap
  - INSTANCE=multi-instance-ubuntu-1404
  - INSTANCE=multi-instance-ubuntu-1404 CHEF_VERSION=12.7.2
  - INSTANCE=multi-instance-ubuntu-1604
  - INSTANCE=multi-instance-ubuntu-1604 CHEF_VERSION=12.7.2

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
